name: Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Information rustc
        run: rustc --version

      - name: Information cargo
        run: cargo --version

      - name: Run cargo check
        run: cargo check
