name: Check

on: [push]

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest Rust lang
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Information rustc
        run: rustc --version

      - name: Information cargo
        run: cargo --version

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
